"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from testdk.types import BaseModel
from typing_extensions import TypedDict


class AsyncResponseTypedDict(TypedDict):
    id: str
    polling_url: str


class AsyncResponse(BaseModel):
    id: str

    polling_url: str
