"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from testdk.types import BaseModel
from typing_extensions import TypedDict


class DeleteFinetuneResponseTypedDict(TypedDict):
    status: str
    r"""Status of the deletion"""
    message: str
    r"""Message about the deletion"""
    deleted_finetune_id: str
    r"""ID of the deleted finetune"""
    timestamp: str
    r"""Timestamp of the deletion"""


class DeleteFinetuneResponse(BaseModel):
    status: str
    r"""Status of the deletion"""

    message: str
    r"""Message about the deletion"""

    deleted_finetune_id: str
    r"""ID of the deleted finetune"""

    timestamp: str
    r"""Timestamp of the deletion"""
