"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseFillV1FluxPro10FillPostTypedDict = TypeAliasType(
    "ResponseFillV1FluxPro10FillPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseFillV1FluxPro10FillPost = TypeAliasType(
    "ResponseFillV1FluxPro10FillPost", Union[AsyncResponse, AsyncWebhookResponse]
)
r"""Successful Response"""
