"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from testdk.types import BaseModel
from testdk.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class FinetuneDetailsV1FinetuneDetailsGetRequestTypedDict(TypedDict):
    finetune_id: str


class FinetuneDetailsV1FinetuneDetailsGetRequest(BaseModel):
    finetune_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
