"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from testdk.types import BaseModel
from typing_extensions import TypedDict


class FinetuneDetailsTypedDict(TypedDict):
    r"""Details about the parameters used for finetuning"""


class FinetuneDetails(BaseModel):
    r"""Details about the parameters used for finetuning"""


class FinetuneDetailResponseTypedDict(TypedDict):
    finetune_details: FinetuneDetailsTypedDict
    r"""Details about the parameters used for finetuning"""


class FinetuneDetailResponse(BaseModel):
    finetune_details: FinetuneDetails
    r"""Details about the parameters used for finetuning"""
