"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseFluxPro10CannyFinetunedV1FluxPro10CannyFinetunedPostTypedDict = TypeAliasType(
    "ResponseFluxPro10CannyFinetunedV1FluxPro10CannyFinetunedPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseFluxPro10CannyFinetunedV1FluxPro10CannyFinetunedPost = TypeAliasType(
    "ResponseFluxPro10CannyFinetunedV1FluxPro10CannyFinetunedPost",
    Union[AsyncResponse, AsyncWebhookResponse],
)
r"""Successful Response"""
