"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseFluxDevV1FluxDevPostTypedDict = TypeAliasType(
    "ResponseFluxDevV1FluxDevPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseFluxDevV1FluxDevPost = TypeAliasType(
    "ResponseFluxDevV1FluxDevPost", Union[AsyncResponse, AsyncWebhookResponse]
)
r"""Successful Response"""
