"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseFluxProFinetunedV1FluxProFinetunedPostTypedDict = TypeAliasType(
    "ResponseFluxProFinetunedV1FluxProFinetunedPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseFluxProFinetunedV1FluxProFinetunedPost = TypeAliasType(
    "ResponseFluxProFinetunedV1FluxProFinetunedPost",
    Union[AsyncResponse, AsyncWebhookResponse],
)
r"""Successful Response"""
