"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .outputformat import OutputFormat
from pydantic import model_serializer
from testdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FluxUltraInputTypedDict(TypedDict):
    prompt: NotRequired[Nullable[str]]
    r"""The prompt to use for image generation."""
    prompt_upsampling: NotRequired[bool]
    r"""Whether to perform upsampling on the prompt. If active, automatically modifies the prompt for more creative generation."""
    seed: NotRequired[Nullable[int]]
    r"""Optional seed for reproducibility. If not provided, a random seed will be used."""
    aspect_ratio: NotRequired[str]
    r"""Aspect ratio of the image between 21:9 and 9:21"""
    safety_tolerance: NotRequired[int]
    r"""Tolerance level for input and output moderation. Between 0 and 6, 0 being most strict, 6 being least strict."""
    output_format: NotRequired[Nullable[OutputFormat]]
    r"""Output format for the generated image. Can be 'jpeg' or 'png'."""
    raw: NotRequired[bool]
    r"""Generate less processed, more natural-looking images"""
    image_prompt: NotRequired[Nullable[str]]
    r"""Optional image to remix in base64 format"""
    image_prompt_strength: NotRequired[float]
    r"""Blend between the prompt and the image prompt"""
    webhook_url: NotRequired[Nullable[str]]
    r"""URL to receive webhook notifications"""
    webhook_secret: NotRequired[Nullable[str]]
    r"""Optional secret for webhook signature verification"""


class FluxUltraInput(BaseModel):
    prompt: OptionalNullable[str] = UNSET
    r"""The prompt to use for image generation."""

    prompt_upsampling: Optional[bool] = False
    r"""Whether to perform upsampling on the prompt. If active, automatically modifies the prompt for more creative generation."""

    seed: OptionalNullable[int] = UNSET
    r"""Optional seed for reproducibility. If not provided, a random seed will be used."""

    aspect_ratio: Optional[str] = "16:9"
    r"""Aspect ratio of the image between 21:9 and 9:21"""

    safety_tolerance: Optional[int] = 2
    r"""Tolerance level for input and output moderation. Between 0 and 6, 0 being most strict, 6 being least strict."""

    output_format: OptionalNullable[OutputFormat] = UNSET
    r"""Output format for the generated image. Can be 'jpeg' or 'png'."""

    raw: Optional[bool] = False
    r"""Generate less processed, more natural-looking images"""

    image_prompt: OptionalNullable[str] = UNSET
    r"""Optional image to remix in base64 format"""

    image_prompt_strength: Optional[float] = 0.1
    r"""Blend between the prompt and the image prompt"""

    webhook_url: OptionalNullable[str] = UNSET
    r"""URL to receive webhook notifications"""

    webhook_secret: OptionalNullable[str] = UNSET
    r"""Optional secret for webhook signature verification"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "prompt",
            "prompt_upsampling",
            "seed",
            "aspect_ratio",
            "safety_tolerance",
            "output_format",
            "raw",
            "image_prompt",
            "image_prompt_strength",
            "webhook_url",
            "webhook_secret",
        ]
        nullable_fields = [
            "prompt",
            "seed",
            "output_format",
            "image_prompt",
            "webhook_url",
            "webhook_secret",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
