"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseFluxPro11V1FluxPro11PostTypedDict = TypeAliasType(
    "ResponseFluxPro11V1FluxPro11PostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseFluxPro11V1FluxPro11Post = TypeAliasType(
    "ResponseFluxPro11V1FluxPro11Post", Union[AsyncResponse, AsyncWebhookResponse]
)
r"""Successful Response"""
