"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseFluxPro10FillFinetunedV1FluxPro10FillFinetunedPostTypedDict = TypeAliasType(
    "ResponseFluxPro10FillFinetunedV1FluxPro10FillFinetunedPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseFluxPro10FillFinetunedV1FluxPro10FillFinetunedPost = TypeAliasType(
    "ResponseFluxPro10FillFinetunedV1FluxPro10FillFinetunedPost",
    Union[AsyncResponse, AsyncWebhookResponse],
)
r"""Successful Response"""
