"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseGenerateBigblueFinetunedV1FluxPro11UltraFinetunedPostTypedDict = TypeAliasType(
    "ResponseGenerateBigblueFinetunedV1FluxPro11UltraFinetunedPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseGenerateBigblueFinetunedV1FluxPro11UltraFinetunedPost = TypeAliasType(
    "ResponseGenerateBigblueFinetunedV1FluxPro11UltraFinetunedPost",
    Union[AsyncResponse, AsyncWebhookResponse],
)
r"""Successful Response"""
