"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseGenerateBigblueV1FluxPro11UltraPostTypedDict = TypeAliasType(
    "ResponseGenerateBigblueV1FluxPro11UltraPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseGenerateBigblueV1FluxPro11UltraPost = TypeAliasType(
    "ResponseGenerateBigblueV1FluxPro11UltraPost",
    Union[AsyncResponse, AsyncWebhookResponse],
)
r"""Successful Response"""
