"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from testdk.types import BaseModel
from typing import Any, List
from typing_extensions import TypedDict


class MyFinetunesResponseTypedDict(TypedDict):
    finetunes: List[Any]
    r"""List of finetunes created by the user"""


class MyFinetunesResponse(BaseModel):
    finetunes: List[Any]
    r"""List of finetunes created by the user"""
