"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .asyncresponse import AsyncResponse, AsyncResponseTypedDict
from .asyncwebhookresponse import AsyncWebhookResponse, AsyncWebhookResponseTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ResponseProDepthV1FluxPro10DepthPostTypedDict = TypeAliasType(
    "ResponseProDepthV1FluxPro10DepthPostTypedDict",
    Union[AsyncResponseTypedDict, AsyncWebhookResponseTypedDict],
)
r"""Successful Response"""


ResponseProDepthV1FluxPro10DepthPost = TypeAliasType(
    "ResponseProDepthV1FluxPro10DepthPost", Union[AsyncResponse, AsyncWebhookResponse]
)
r"""Successful Response"""
